development:
  adapter: mysql2
  database: pizza_restaurant
  pool: 5
  username: root
  password: password

test:
  adapter: mysql2
  database: pizza_restaurant_test
  pool: 5
  username: root
  password: password
