development:
  adapter: postgresql
  encoding: unicode
  database: pizza_restaurant
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: pizza_restaurant_test
  pool: 5
  username: postgres
  password: password
